### ISSUE TITLE
Initialized Maven projects should include a Maven Wrapper

### ISSUE THREAD

**Issue by spilth** [spilth/savant2#4]
As a Java developer
I want new Maven projects to include their own Maven wrapper
So that I don't have to install or manage Maven globally on my system

## Acceptance Criteria

Given I have initialized a Maven project using Savant
When I `cd` into the new project directory
Then I should see `mvnw` command and it's associated `.mvn` directory

## For Discussion

- Implemented via https://github.com/takari/maven-wrapper?
- Should this be the default behavior?
- Should there be a command-line flag for turning this behavior on/off?

**Comment by dguardado** [comment]
- Takari maven-wrapper seems like it's being pulled into official Maven so it seems like the way to go until maven takes care of it out of the box
- I think simplest thing would be to make it default behavior and make it non-configurable. People could always just not use it and delete the wrapper files
- I don't tend to use mvnw much myself, but it seems pretty popular, and conceptually it seems pretty helpful, even if there are other ways to achieve the same goal.
